version: '3'

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/neo"
      NEO4J_dbms_memory_heap_max__size: 4G
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*, algo.*"
      NEO4J_kafka_auto_offset_reset: earliest
      NEO4J_kafka_group_id: neo4j
      NEO4J_kafka_zookeeper_connect: zookeeper:2181
      NEO4J_kafka_bootstrap_servers: broker:9093
      NEO4J_streams_source_topic_nodes_users: User{*}
      NEO4J_dbms_logs_debug_level: DEBUG
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
 